# Data Science Pandas

## Tasks Today:

1) <b>Pandas</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Tabular Data Structures <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - from_dict() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - read_csv() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) <b>In-Class Exercise #1</b> <br>
  &nbsp;&nbsp;&nbsp;&nbsp; d) Built-In Methods <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - head() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - tail() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - describe() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - sort_values() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - keys() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - .columns <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Accessing Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Indexing <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - df.loc <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - df.iloc <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) <b>In-Class Exercise #2</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Filtration <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Conditionals <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Column Transformations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Generating a New Column w/Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - User Defined Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Aggregations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Type of groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - mean() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() w/Multiple Columns <br>

## Pandas <br>

<p>Pandas is a flexible data analysis library built on top of NumPy that is excellent for working with tabular data. It is currently the de-facto standard for Python-based data analysis, and fluency in Pandas will do wonders for your productivity and frankly your resume. It is one of the fastest ways of getting from zero to answer in existence. </p>

<ul>
    <li>Pandas is a Python module, written in C. The Pandas module is a high performance, highly efficient, and high level data analysis library. It allows us to work with large sets of data called dataframes.</li>
    <li>Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.)</li>
    <li>Dataframe = Spreadsheet (has column headers, index, etc.)</li>
</ul>

### Importing

In [ ]:
!pip install pandas

In [1]:
import numpy as np
import pandas as pd

# always use pd, standard for data science

### Tabular data structures <br>
<p>The central object of study in Pandas is the DataFrame, which is a tabular data structure with rows and columns like an excel spreadsheet. The first point of discussion is the creation of dataframes both from native Python dictionaries, and text files through the Pandas I/O system.</p>

In [3]:
names = ['Alice', 'Bob','Carl','Devin','Edgar','Frank','Gunther','Helga','Ingrid','Juanita']
ages = np.random.randint(18,35,len(names))

my_peeps={
    'name': names,
    'age': ages
}

my_peeps

{'name': ['Alice',
  'Bob',
  'Carl',
  'Devin',
  'Edgar',
  'Frank',
  'Gunther',
  'Helga',
  'Ingrid',
  'Juanita'],
 'age': array([25, 27, 23, 21, 28, 25, 29, 18, 31, 33])}

##### from_dict()

<p>Let's convert our not-so-useful-for-analysis dict into a Pandas dataframe. We can use the from_dict function to do this easily using Pandas:</p>

In [4]:
df = pd.DataFrame.from_dict(my_peeps)

df

      name  age
0    Alice   25
1      Bob   27
2     Carl   23
3    Devin   21
4    Edgar   28
5    Frank   25
6  Gunther   29
7    Helga   18
8   Ingrid   31
9  Juanita   33

##### read_csv()

<p>Pandas also provides a function to read a csv into a DataFrame. Let's take a look at this using the Marathon data from yesterday's class</p>

In [12]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

# marathon = pd.read_csv('boston_marathon2017_edited(1).csv', sep=',')

# marathon

### In-Class Exercise #1 - Read in the Spotify CSV<br>
<p>Use the pandas read_csv() method to read in the stats about the top 100 streamed songs on spotify.</p>

In [11]:
spotify = pd.read_csv('spotify_top_100_streamed.csv', sep = ',')

spotify

,title,artist,top genre,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity
0,Blinding Lights,The Weeknd,canadian contemporary r&b,2020,171,73,51,-6,9,33,200,0,6,91
1,Watermelon Sugar,Harry Styles,pop,2019,95,82,55,-4,34,56,174,12,5,88
2,Mood (feat. iann dior),24kGoldn,cali rap,2021,91,72,70,-4,32,73,141,17,4,88
3,Someone You Loved,Lewis Capaldi,pop,2019,110,41,50,-6,11,45,182,75,3,86
4,Perfect,Ed Sheeran,pop,2017,95,45,60,-6,11,17,263,16,2,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,One Dance,Drake,canadian hip hop,2016,104,61,79,-6,32,43,174,1,6,66
96,Sugar,Maroon 5,pop,2015,120,79,75,-7,9,88,235,6,3,66
97,Emotions,Mark Mendy,pop dance,2021,126,83,66,-5,40,74,172,5,29,66
98,Cold Water,Major Lazer,dance pop,2018,93,80,61,-5,16,50,185,7,4,56
99,I Took A Pill In Ibiza - Seeb Remix,Mike Posner,dance pop,2016,102,73,67,-7,9,66,198,3,10,53

### Built-In Methods <br>

<p>These are methods that are frequently used when using Pandas to make your life easier. It is possible to spend a whole week simply exploring the built-in functions supported by DataFrames in Pandas. Here however, we will simply highlight a few ones that might be useful, to give you an idea of what's possible out of the box with Pandas:</p>

##### head()

In [16]:
# DataFrame.head()  -- Accepts integer parameter(gives access to more rows)
spotify.head(50)

,title,artist,top genre,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity
0,Blinding Lights,The Weeknd,canadian contemporary r&b,2020,171,73,51,-6,9,33,200,0,6,91
1,Watermelon Sugar,Harry Styles,pop,2019,95,82,55,-4,34,56,174,12,5,88
2,Mood (feat. iann dior),24kGoldn,cali rap,2021,91,72,70,-4,32,73,141,17,4,88
3,Someone You Loved,Lewis Capaldi,pop,2019,110,41,50,-6,11,45,182,75,3,86
4,Perfect,Ed Sheeran,pop,2017,95,45,60,-6,11,17,263,16,2,86
5,Believer,Imagine Dragons,modern rock,2017,125,78,78,-4,8,67,204,6,13,86
6,lovely (with Khalid),Billie Eilish,electropop,2018,115,30,35,-10,10,12,200,93,3,86
7,Circles,Post Malone,dfw rap,2019,120,76,70,-3,9,55,215,19,4,86
8,Shape of You,Ed Sheeran,pop,2017,96,65,83,-3,9,93,234,58,8,85
9,Memories,Maroon 5,pop,2021,91,33,78,-7,8,60,189,84,6,85
10,Closer,The Chainsmokers,dance pop,2016,95,52,75,-6,11,66,245,41,3,84
11,bad guy,Billie Eilish,electropop,2019,135,43,70,-11,10,56,194,33,38,84
12,Say You Won't Let Go,James Arthur,pop,2016,85,56,36,-7,9,49,211,70,6,84
13,Lucid Dreams,Juice WRLD,chicago rap,2018,84,57,51,-7,34,22,240,35,20,84
14,All of Me,John Legend,neo soul,2013,120,26,42,-7,13,33,270,92,3,84
15,7 rings,Ariana Grande,dance pop,2019,140,32,78,-11,9,33,179,59,33,84
16,Jocelyn Flores,XXXTENTACION,emo rap,2017,134,39,87,-9,30,44,119,47,24,84
17,goosebumps,Travis Scott,rap,2016,130,73,84,-3,15,43,244,8,5,84
18,Wake Me Up,Avicii,dance pop,2013,124,78,53,-6,16,64,247,0,5,84
19,ROCKSTAR (feat. Roddy Ricch),DaBaby,north carolina hip hop,2020,90,69,75,-8,10,50,182,25,16,84
20,rockstar (feat. 21 Savage),Post Malone,dfw rap,2018,160,52,59,-6,13,13,218,12,7,83
21,Photograph,Ed Sheeran,pop,2014,108,38,61,-10,10,20,259,61,5,83
22,SAD!,XXXTENTACION,emo rap,2018,75,61,74,-5,12,47,167,26,14,83
23,SICKO MODE,Travis Scott,rap,2018,155,73,83,-4,12,45,313,1,22,83
24,Stressed Out,Twenty One Pilots,modern rock,2015,170,64,73,-6,6,65,202,5,14,83
25,Roses - Imanbek Remix,SAINt JHN,melodic rap,2019,122,72,77,-5,35,90,177,2,5,83
26,The Box,Roddy Ricch,melodic rap,2019,117,59,90,-7,79,64,197,10,6,83
27,The Hills,The Weeknd,canadian contemporary r&b,2015,113,56,59,-7,14,14,242,7,5,83
28,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,2018,90,48,76,-6,7,91,158,56,5,82
29,Thinking out Loud,Ed Sheeran,pop,2014,79,45,78,-6,18,59,282,47,3,82
30,Starboy,The Weeknd,canadian contemporary r&b,2016,186,59,68,-7,14,49,230,14,28,82
31,Love Yourself,Justin Bieber,canadian pop,2015,100,38,61,-10,28,52,234,84,44,82
32,Something Just Like This,The Chainsmokers,dance pop,2017,103,64,62,-7,16,45,247,5,3,82
33,Shallow,Lady Gaga,dance pop,2018,96,39,57,-6,23,32,216,37,3,82
34,Thunder,Imagine Dragons,modern rock,2017,168,82,61,-5,15,29,187,1,4,82
35,XO Tour Llif3,Lil Uzi Vert,melodic rap,2017,155,75,73,-6,11,40,183,0,23,82
36,Take Me To Church,Hozier,irish singer-songwriter,2014,129,66,57,-5,12,44,242,63,5,82
37,Happier,Marshmello,brostep,2018,100,79,69,-3,17,67,214,19,5,82
38,"thank u, next",Ariana Grande,dance pop,2019,107,65,72,-6,10,41,207,23,7,82
39,Counting Stars,OneRepublic,dance pop,2013,122,71,66,-5,12,48,257,7,4,82
40,Can't Hold Us - feat. Ray Dalton,Macklemore & Ryan Lewis,pop rap,2012,146,92,64,-4,9,85,258,3,8,82
41,Señorita,Shawn Mendes,canadian pop,2019,117,54,76,-6,9,75,191,4,3,81
42,God's Plan,Drake,canadian hip hop,2018,77,45,75,-9,55,36,199,3,11,81
43,Don't Start Now,Dua Lipa,dance pop,2020,124,79,79,-5,10,68,183,1,8,81
44,Bohemian Rhapsody - Remastered 2011,Queen,classic rock,1975,71,40,41,-10,30,22,354,27,5,81
45,HUMBLE.,Kendrick Lamar,conscious hip hop,2017,150,62,91,-7,10,42,177,0,10,81
46,Let Me Love You,DJ Snake,dance pop,2016,100,72,65,-5,14,16,206,9,3,81
47,Congratulations,Post Malone,dfw rap,2016,123,80,63,-4,25,49,220,22,4,81
48,Stay With Me,Sam Smith,dance pop,2014,84,42,42,-6,11,18,173,59,4,81
49,Treat You Better,Shawn Mendes,canadian pop,2017,83,82,44,-4,11,75,188,11,34,81

##### tail()

In [18]:
# DataFrame.tail()  -- Accepts integer parameter(gives access to more rows)
spotify.tail(50)

,title,artist,top genre,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity
50,Uptown Funk (feat. Bruno Mars),Mark Ronson,dance pop,2015,115,61,86,-7,3,93,270,1,8,81
51,I Like Me Better,Lauv,dance pop,2018,92,51,75,-8,10,42,197,54,25,81
52,when the party's over,Billie Eilish,electropop,2019,83,11,37,-14,9,20,196,98,10,81
53,Mr. Brightside,The Killers,alternative rock,2004,148,91,35,-5,10,24,223,0,7,81
54,Dance Monkey,Tones And I,australian pop,2019,98,59,82,-6,15,51,209,69,9,80
55,Havana (feat. Young Thug),Camila Cabello,dance pop,2018,105,52,77,-4,13,39,217,18,3,80
56,Better Now,Post Malone,dfw rap,2018,145,58,68,-6,14,34,231,33,4,80
57,I Don't Care (with Justin Bieber),Ed Sheeran,pop,2019,102,68,80,-5,9,84,220,9,4,80
58,Unforgettable,French Montana,gangster rap,2017,98,77,73,-5,10,73,234,3,12,80
59,Too Good At Goodbyes,Sam Smith,dance pop,2017,92,37,68,-8,17,48,201,64,4,80
60,Riptide,Vance Joy,folk-pop,2014,102,73,48,-7,15,51,204,43,4,80
61,That's What I Like,Bruno Mars,dance pop,2016,134,56,85,-5,9,86,207,1,4,80
62,See You Again (feat. Charlie Puth),Wiz Khalifa,dance pop,2015,80,48,69,-8,6,28,230,37,8,80
63,One Kiss (with Dua Lipa),Calvin Harris,dance pop,2018,124,86,79,-3,8,59,215,4,11,80
64,Heathens,Twenty One Pilots,modern rock,2016,90,40,73,-9,11,55,196,8,3,80
65,Demons,Imagine Dragons,modern rock,2012,90,71,51,-3,27,43,178,19,3,80
66,Youngblood,5 Seconds of Summer,boy band,2018,120,85,60,-5,12,15,203,2,46,80
67,Old Town Road - Remix,Lil Nas X,lgbtq+ hip hop,2019,136,62,88,-6,11,64,157,5,10,80
68,I'm Yours,Jason Mraz,acoustic pop,2008,151,46,69,-8,11,72,242,60,5,80
69,Attention,Charlie Puth,dance pop,2018,100,61,78,-5,13,80,209,11,5,80
70,New Rules,Dua Lipa,dance pop,2017,116,70,76,-6,15,61,209,0,7,79
71,Sorry,Justin Bieber,canadian pop,2015,100,76,65,-4,30,41,201,8,5,79
72,Don't Let Me Down,The Chainsmokers,dance pop,2016,160,87,53,-5,14,42,208,16,17,79
73,7 Years,Lukas Graham,danish pop,2016,120,47,77,-6,39,34,237,29,5,79
74,I Like It,Cardi B,dance pop,2018,136,73,82,-4,37,65,253,10,13,79
75,I Fall Apart,Post Malone,dfw rap,2016,144,54,56,-5,20,29,223,7,4,79
76,We Don't Talk Anymore (feat. Selena Gomez),Charlie Puth,dance pop,2016,100,56,73,-8,18,35,218,62,13,79
77,Can't Feel My Face,The Weeknd,canadian contemporary r&b,2015,108,77,71,-6,11,58,214,11,4,79
78,Despacito,Luis Fonsi,latin,2019,178,80,66,-5,7,84,229,20,15,78
79,Psycho (feat. Ty Dolla $ign),Post Malone,dfw rap,2018,140,56,75,-8,11,46,221,55,11,78
80,Stitches,Shawn Mendes,canadian pop,2015,150,75,75,-7,5,75,207,2,7,77
81,What Do You Mean?,Justin Bieber,canadian pop,2015,125,57,85,-8,8,79,206,59,10,77
82,Wonderwall - Remastered,Oasis,beatlesque,1995,174,90,38,-4,19,47,259,0,4,77
83,Radioactive,Imagine Dragons,modern rock,2012,136,78,45,-4,67,24,187,11,6,76
84,Eastside (with Halsey & Khalid),benny blanco,electropop,2018,89,68,56,-8,12,32,174,56,32,76
85,Cheerleader - Felix Jaehn Remix Radio Edit,OMI,dance pop,2015,118,69,78,-6,16,60,181,17,3,76
86,Cheap Thrills,Sia,australian dance,2016,90,70,63,-6,9,73,212,5,11,75
87,Girls Like You (feat. Cardi B) - Cardi B Version,Maroon 5,pop,2018,125,54,85,-7,13,45,236,57,5,74
88,Faded,Alan Walker,electro house,2015,90,65,59,-5,11,17,213,3,3,72
89,Let Her Go,Passenger,folk-pop,2013,76,54,45,-7,11,22,253,36,7,72
90,CAN'T STOP THE FEELING! (from DreamWorks Anima...,Justin Timberlake,dance pop,2016,113,83,67,-6,10,70,238,1,7,72
91,Lean On,Major Lazer,dance pop,2015,98,81,72,-3,56,27,177,0,6,71
92,Despacito - Remix,Luis Fonsi,latin,2019,178,80,65,-4,7,86,230,23,18,70
93,Lose Yourself,Eminem,detroit hip hop,2014,171,74,69,-5,37,6,321,1,27,70
94,Without Me (with Juice WRLD),Halsey,dance pop,2019,136,51,74,-6,18,45,229,36,7,67
95,One Dance,Drake,canadian hip hop,2016,104,61,79,-6,32,43,174,1,6,66
96,Sugar,Maroon 5,pop,2015,120,79,75,-7,9,88,235,6,3,66
97,Emotions,Mark Mendy,pop dance,2021,126,83,66,-5,40,74,172,5,29,66
98,Cold Water,Major Lazer,dance pop,2018,93,80,61,-5,16,50,185,7,4,56
99,I Took A Pill In Ibiza - Seeb Remix,Mike Posner,dance pop,2016,102,73,67,-7,9,66,198,3,10,53

##### shape

In [17]:
# The dataframe has a shape property, just like a NumPy matrix. 
# print(df.shape) -- DataFrame.shape -- No Parameter
print(spotify.shape)
print(df.shape)

(100, 14)
(10, 2)

##### keys()

In [19]:
# Access all of the keys/columns of the dataframe
# Dataframe.keys()
print(spotify.keys())
print(type(spotify.keys()))

Index(['title', 'artist', 'top genre', 'year', 'beats.per.minute', 'energy',
       'danceability', 'loudness.dB', 'liveness', 'valance', 'length',
       'acousticness', 'speechiness', 'popularity'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

##### describe() <br>
<p>Probably one of the most important methods to understand...</p>

In [20]:
# Collect summary statistics in one line
# DataFrame.describe() -- Accepts parameters (include, exclude)
spotify.describe()

,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,2015.960000,116.970000,62.680000,66.96000,-6.100000,16.860000,49.970000,214.530000,24.95000,9.930000,79.670000
std,5.327497,27.470629,16.491737,13.60401,1.987334,12.972403,21.737857,35.934974,26.27876,9.424077,5.905065
min,1975.000000,71.000000,11.000000,35.00000,-14.000000,3.000000,6.000000,119.000000,0.00000,2.000000,53.000000
25%,2015.000000,95.000000,52.000000,59.00000,-7.000000,10.000000,33.750000,190.500000,4.00000,4.000000,79.000000
50%,2017.000000,115.000000,64.500000,69.00000,-6.000000,12.000000,48.000000,210.000000,13.00000,6.000000,81.000000
75%,2018.000000,135.250000,76.000000,77.00000,-5.000000,17.250000,66.000000,234.250000,41.50000,11.000000,83.000000
max,2021.000000,186.000000,92.000000,91.00000,-3.000000,79.000000,93.000000,354.000000,98.00000,46.000000,91.000000

In [21]:
spotify.describe(include='all')

,title,artist,top genre,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity
count,100,100,100,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
unique,100,64,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Blinding Lights,Post Malone,dance pop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,7,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2015.960000,116.970000,62.680000,66.96000,-6.100000,16.860000,49.970000,214.530000,24.95000,9.930000,79.670000
std,NaN,NaN,NaN,5.327497,27.470629,16.491737,13.60401,1.987334,12.972403,21.737857,35.934974,26.27876,9.424077,5.905065
min,NaN,NaN,NaN,1975.000000,71.000000,11.000000,35.00000,-14.000000,3.000000,6.000000,119.000000,0.00000,2.000000,53.000000
25%,NaN,NaN,NaN,2015.000000,95.000000,52.000000,59.00000,-7.000000,10.000000,33.750000,190.500000,4.00000,4.000000,79.000000
50%,NaN,NaN,NaN,2017.000000,115.000000,64.500000,69.00000,-6.000000,12.000000,48.000000,210.000000,13.00000,6.000000,81.000000
75%,NaN,NaN,NaN,2018.000000,135.250000,76.000000,77.00000,-5.000000,17.250000,66.000000,234.250000,41.50000,11.000000,83.000000
max,NaN,NaN,NaN,2021.000000,186.000000,92.000000,91.00000,-3.000000,79.000000,93.000000,354.000000,98.00000,46.000000,91.000000

##### sort_values()

In [23]:
# Sort based on many labels, with left-to-right priority
# sorted_data = data.sort_values('ages').reset_index()

# DataFrame.sort_values('key')

sorted_ages= df.sort_values('age')

sorted_ages

      name  age
7    Helga   18
3    Devin   21
2     Carl   23
0    Alice   25
5    Frank   25
1      Bob   27
4    Edgar   28
6  Gunther   29
8   Ingrid   31
9  Juanita   33

In [26]:
sorted_ages.reset_index(drop=True, inplace = True)

sorted_ages

      name  age
0    Helga   18
1    Devin   21
2     Carl   23
3    Alice   25
4    Frank   25
5      Bob   27
6    Edgar   28
7  Gunther   29
8   Ingrid   31
9  Juanita   33

##### .columns

In [28]:
# will show all cols headers
# DataFrame.columns is an attribute

print(spotify.columns)
print(f"Columns type:{type(spotify.columns)}")

Index(['title', 'artist', 'top genre', 'year', 'beats.per.minute', 'energy',
       'danceability', 'loudness.dB', 'liveness', 'valance', 'length',
       'acousticness', 'speechiness', 'popularity'],
      dtype='object')
Columns type:<class 'pandas.core.indexes.base.Index'>

### Accessing Data <br>

##### Indexing

<p>You can directly select a column of a dataframe just like you would a dict. The result is a Pandas 'Series' object.</p>

In [31]:
# Currently working with a pandas dataframe object
print(type(spotify))

# index a column of the dataframe - df['column_name']
title = spotify['title']
print(title)

<class 'pandas.core.frame.DataFrame'>
0                         Blinding Lights
1                        Watermelon Sugar
2                  Mood (feat. iann dior)
3                       Someone You Loved
4                                 Perfect
                     ...
95                              One Dance
96                                  Sugar
97                               Emotions
98                             Cold Water
99    I Took A Pill In Ibiza - Seeb Remix
Name: title, Length: 100, dtype: object

In [33]:
# index a series object - series[index] 0 based

print(title[52])

when the party's over

In [37]:
energy = spotify['energy']

length = spotify['length']

energy
length

0     200
1     174
2     141
3     182
4     263
     ...
95    174
96    235
97    172
98    185
99    198
Name: length, Length: 100, dtype: int64

#### Accessing Multiple Columns

In [38]:
df.loc[0]

name    Alice
age        25
Name: 0, dtype: object

In [40]:
sorted_data= df.sort_values('age')
sorted_data

      name  age
7    Helga   18
3    Devin   21
2     Carl   23
0    Alice   25
5    Frank   25
1      Bob   27
4    Edgar   28
6  Gunther   29
8   Ingrid   31
9  Juanita   33

In [42]:
sorted_data.loc[0]

name    Alice
age        25
Name: 0, dtype: object

##### df.loc

<p>Along the horizontal dimension, rows of Pandas DataFrames are Row objects. You will notice there is a third column present in the DataFrame - this is the $\textit{index}$. It is automatically generated as a row number, but can be reassigned to a column of your choice using the DataFrame.set_index(colname) method. We can use it to access particular Pandas $\textit{rows}$, which are also Series objects:</p>

##### df.iloc
<p>df.iloc is purely integer-location based indexing for selection by position.</p>

### In-Class Exercise #2 - Most Upbeat Songs in Top 100 <br>
<p>Return back a dataframe showing the Title, Artist, Year and Beats Per Minute for the 10 most upbeat songs (as determined by BPM)</p>

In [47]:
spotify[['title','artist','year','beats.per.minute']].sort_values('beats.per.minute').tail(10)

                         title             artist  year  beats.per.minute
72           Don't Let Me Down   The Chainsmokers  2016               160
20  rockstar (feat. 21 Savage)        Post Malone  2018               160
34                     Thunder    Imagine Dragons  2017               168
24                Stressed Out  Twenty One Pilots  2015               170
93               Lose Yourself             Eminem  2014               171
0              Blinding Lights         The Weeknd  2020               171
82     Wonderwall - Remastered              Oasis  1995               174
78                   Despacito         Luis Fonsi  2019               178
92           Despacito - Remix         Luis Fonsi  2019               178
30                     Starboy         The Weeknd  2016               186

### Filtration <br>
<p>Let's look at how to filter dataframes for rows that fulfill a specific conditon.</p>

##### Conditionals

In [ ]:
# Conditional boolean dataframe

##### Subsetting

In [ ]:
# exactly like numpy

### Column Transformations <br>
<p>Rarely, if ever, will the columns in the original raw dataframe read from CSV or database table be the ones you actually need for your analysis. You will spend lots of time constantly transforming columns or groups of columns using general computational operations to produce new ones that are functions of the old ones. Pandas has full support for this: Consider the following fake dataframe containing member since year and the yearly dues for member:</p>

In [50]:
!pip install faker

Collecting faker
  Downloading Faker-12.1.0-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 3.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.4 in /Users/Allison/opt/anaconda3/lib/python3.9/site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/Allison/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-12.1.0

In [51]:
from faker import Faker

In [52]:
fake = Faker()

In [53]:
pay_options = {
    0: 100,
    1: 150,
    2: 200
}

membership = {
    'member_id': [np.random.randint(1000,2000) for x in range(20)],
    'name': [fake.name() for n in range(20)],
    'member_since': [np.random.randint(2000, 2021) for i in range(20)],
    'yearly_dues': [pay_options[np.random.randint(0,3)] for b in range(20)]
}

customers = pd.DataFrame.from_dict(membership)

In [54]:
customers

    member_id               name  member_since  yearly_dues
0        1278        John Sexton          2014          200
1        1727      Joseph Cooper          2012          100
2        1823        Amber Cantu          2007          100
3        1180        Leslie Dunn          2006          150
4        1481        Joshua Pham          2018          100
5        1158      Chelsea Smith          2005          100
6        1821    Carolyn Johnson          2013          200
7        1895      Rachel Stuart          2009          150
8        1886      Lawrence Boyd          2000          200
9        1057         Kara Moore          2020          200
10       1997     Stephanie Reed          2008          150
11       1369        Susan Smith          2008          200
12       1199  Brenda Wright DDS          2014          100
13       1706     Scott Martinez          2011          150
14       1490    Stephanie Parks          2008          100
15       1658   Amanda Rodriguez          2015          100
16       1025    Steven Buchanan          2012          150
17       1713    Randall Brennan          2006          100
18       1670        Caleb Lopez          2010          150
19       1309       Angela White          2000          200

##### Generating a New Column w/Data

In [58]:
customers['total_paid']= customers['member_since'] * customers['yearly_dues']
customers

    member_id               name  member_since  yearly_dues  total_paid
0        1278        John Sexton          2014          200      402800
1        1727      Joseph Cooper          2012          100      201200
2        1823        Amber Cantu          2007          100      200700
3        1180        Leslie Dunn          2006          150      300900
4        1481        Joshua Pham          2018          100      201800
5        1158      Chelsea Smith          2005          100      200500
6        1821    Carolyn Johnson          2013          200      402600
7        1895      Rachel Stuart          2009          150      301350
8        1886      Lawrence Boyd          2000          200      400000
9        1057         Kara Moore          2020          200      404000
10       1997     Stephanie Reed          2008          150      301200
11       1369        Susan Smith          2008          200      401600
12       1199  Brenda Wright DDS          2014          100      201400
13       1706     Scott Martinez          2011          150      301650
14       1490    Stephanie Parks          2008          100      200800
15       1658   Amanda Rodriguez          2015          100      201500
16       1025    Steven Buchanan          2012          150      301800
17       1713    Randall Brennan          2006          100      200600
18       1670        Caleb Lopez          2010          150      301500
19       1309       Angela White          2000          200      400000

##### User Defined Function

<p>If what you want to do to a column that can't be represented by simple mathematical operations, you can write your own $\textit{user defined function}$ with the full customizability available in Python and any external Python packages, then map it directly onto a column or row. Let's create a function that will return the loyalty status of a member based on their customer tenure. We will then apply that function to each row in our dataframe using the .apply() method:</p>

In [ ]:
def member_loyalty_status(row):
    if row['customer_tenure'] >15:
        return 'platinum'
    elif row['customer_tenure'] > 10:
        return 'gold'
    elif row['customer_tenure '] >5:
        return 'silver'
    else:
        return 'bronze'
    
    customers['loyalty_status']= customers.apply(member_loyalty_status, )

### In-Class Exercise #3 - Create Your Own UDF <br>
<p>Using the Spotify data, create your own UDF which creates a new column called 'Banger' and puts every song with either an energy over 65 or danceability over 70 with a result of 'Yes' in the column if it is and 'No' if it is not.</p>

In [62]:
def banger(row):
    #if the energy is above 65 or the daceability is over 70 return yes 
    #this will be the info in the column
    if row['energy'] > 65 and row['danceability'] > 70:
#         if row['danceability'] > 70
        return 'Yes'
    else:
        return 'no'
#name of the column
#0 axis is index, 1 axis is column
spotify['banger'] = spotify.apply(banger,axis=1)
spotify

,title,artist,top genre,year,beats.per.minute,energy,danceability,loudness.dB,liveness,valance,length,acousticness,speechiness,popularity,banger
0,Blinding Lights,The Weeknd,canadian contemporary r&b,2020,171,73,51,-6,9,33,200,0,6,91,no
1,Watermelon Sugar,Harry Styles,pop,2019,95,82,55,-4,34,56,174,12,5,88,no
2,Mood (feat. iann dior),24kGoldn,cali rap,2021,91,72,70,-4,32,73,141,17,4,88,no
3,Someone You Loved,Lewis Capaldi,pop,2019,110,41,50,-6,11,45,182,75,3,86,no
4,Perfect,Ed Sheeran,pop,2017,95,45,60,-6,11,17,263,16,2,86,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,One Dance,Drake,canadian hip hop,2016,104,61,79,-6,32,43,174,1,6,66,no
96,Sugar,Maroon 5,pop,2015,120,79,75,-7,9,88,235,6,3,66,Yes
97,Emotions,Mark Mendy,pop dance,2021,126,83,66,-5,40,74,172,5,29,66,no
98,Cold Water,Major Lazer,dance pop,2018,93,80,61,-5,16,50,185,7,4,56,no
99,I Took A Pill In Ibiza - Seeb Remix,Mike Posner,dance pop,2016,102,73,67,-7,9,66,198,3,10,53,no

### Aggregations <br>
<p>The raw data plus some transformations is generally only half the story. Your objective is to extract actual insights and actionable conclusions from the data, and that means reducing it from potentially billions of rows to some summary statistics via aggregation functions.</p>

##### groupby() <br>
<p>The .groupby() function is in some ways a 'master' aggregation.</p> 

<p>Data tables will usually reserve one column as a primary key - that is, a column for which each row has a unique value. This is to facilitate access to the exact rows of a data table that a user wants to view. The other columns will often have repeated values, such as the age groups in the above examples. We can use these columns to explore the data using the Pandas API:</p>

##### Type of groupby()

<p>The result is a new dataframe, the columns of which all contain the counts of the grouped field. Notice the type of a grouped dataframe:</p>

<p>This is because simply grouping data doesn't quite make sense without an aggregation function like count() to pair with. In this case, we're counting occurances of the grouped field, but that's not all we can do. We can take averages, standard deviations, mins, maxes and much more! Let's see how this works a bit more:</p>

##### mean()

##### groupby() w/Multiple Columns

<p>We end up with the average age of the groups in the last column, the average tenure in the tenure column, and so on and so forth. You can even split the groups more finely by passing a list of columns to group by:</p>

### Homework Excersise #1 - White Sox Data<br>
<p>Return a dataframe showing the White Sox qualified hitters* in order from best to worst XBHA**.</p>
<p>*A hitter must have at least 100 At Bats (AB's) to qualify</p>
<p>** XBHA is calculated as the number of extra base hits (2B, 3B, HR) divided by the number of At Bats (AB's)</p>

In [64]:
sox = pd.read_csv('../Day1/whitesox_2021_hitting.csv', sep=',')
sox

,Rk,Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
0,1,C,Yasmani Grandal,32,93,375,279,60,67,9,...,0.420,0.520,0.939,157,145,15,3,1,5,0
1,2,1B,José Abreu,34,152,659,566,86,148,30,...,0.351,0.481,0.831,125,272,28,22,0,10,3
2,3,2B,Cesar Hernandez,31,53,217,194,24,45,4,...,0.309,0.299,0.608,69,58,5,1,0,1,2
3,4,SS,Tim Anderson,28,123,551,527,94,163,29,...,0.338,0.469,0.806,118,247,5,1,0,1,1
4,5,3B,Yoan Moncada,26,144,616,520,74,137,33,...,0.375,0.412,0.787,117,214,6,10,0,2,1
5,6,LF,Andrew Vaughn,23,127,469,417,56,98,22,...,0.309,0.396,0.705,92,165,14,6,0,5,0
6,7,CF,Luis Robert,23,68,296,275,42,93,22,...,0.378,0.567,0.946,155,156,4,5,0,2,1
7,8,RF,Adam Eaton,32,58,219,189,33,38,8,...,0.298,0.344,0.642,76,65,5,6,4,0,0
8,9,DH,Yermin Mercedes,28,68,262,240,26,65,9,...,0.328,0.404,0.732,100,97,7,1,0,1,1
9,10,UT,Leury Garcia,30,126,474,415,60,111,22,...,0.335,0.376,0.711,96,156,12,4,9,5,0
10,11,OF,Brian Goodwin,30,72,271,235,33,52,10,...,0.319,0.374,0.693,90,88,2,1,1,1,0
11,12,LF,Eloy Jimenez,24,55,231,213,23,53,10,...,0.303,0.437,0.740,100,93,8,1,0,1,0
12,13,C,Zack Collins,26,78,231,195,25,41,13,...,0.330,0.338,0.669,85,66,4,1,1,0,1
13,14,2B,Nick Madrigal,24,54,215,200,30,61,10,...,0.349,0.425,0.774,112,85,3,3,0,1,0
14,15,MI,Danny Mendick,27,71,186,164,14,36,5,...,0.303,0.287,0.589,64,47,1,2,1,1,0
15,16,DH,Gavin Sheets,25,54,179,160,23,40,8,...,0.324,0.506,0.830,123,81,4,2,0,1,0
16,17,CF,Adam Engel,29,39,140,123,21,31,9,...,0.336,0.496,0.832,124,61,4,5,0,1,0
17,18,CF,Billy Hamilton,30,71,135,127,23,28,8,...,0.242,0.378,0.620,67,48,1,0,3,1,0
18,19,UT,Jake Lamb,30,43,131,113,20,24,2,...,0.321,0.389,0.710,94,44,4,1,0,0,0
19,20,C,Seby Zavala,27,37,104,93,15,17,3,...,0.240,0.376,0.616,66,35,1,1,4,0,0
20,21,3B,Jake Burger,25,15,42,38,5,10,3,...,0.333,0.474,0.807,118,18,2,0,0,0,0
21,22,UT,Romy Gonzalez,24,10,33,32,4,8,3,...,0.273,0.344,0.616,68,11,1,0,0,0,0
22,23,LF,Nick Williams,27,4,13,10,2,0,0,...,0.231,0.000,0.231,-27,0,1,2,0,0,0
23,24,OF,Luis Gonzalez,25,6,11,8,2,2,2,...,0.455,0.500,0.955,163,4,1,0,0,0,0

In [65]:
hitters_qualified= sox.where(sox['AB'] >= 100)

hitters_qualified

,Rk,Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
0,1.0,C,Yasmani Grandal,32.0,93.0,375.0,279.0,60.0,67.0,9.0,...,0.420,0.520,0.939,157.0,145.0,15.0,3.0,1.0,5.0,0.0
1,2.0,1B,José Abreu,34.0,152.0,659.0,566.0,86.0,148.0,30.0,...,0.351,0.481,0.831,125.0,272.0,28.0,22.0,0.0,10.0,3.0
2,3.0,2B,Cesar Hernandez,31.0,53.0,217.0,194.0,24.0,45.0,4.0,...,0.309,0.299,0.608,69.0,58.0,5.0,1.0,0.0,1.0,2.0
3,4.0,SS,Tim Anderson,28.0,123.0,551.0,527.0,94.0,163.0,29.0,...,0.338,0.469,0.806,118.0,247.0,5.0,1.0,0.0,1.0,1.0
4,5.0,3B,Yoan Moncada,26.0,144.0,616.0,520.0,74.0,137.0,33.0,...,0.375,0.412,0.787,117.0,214.0,6.0,10.0,0.0,2.0,1.0
5,6.0,LF,Andrew Vaughn,23.0,127.0,469.0,417.0,56.0,98.0,22.0,...,0.309,0.396,0.705,92.0,165.0,14.0,6.0,0.0,5.0,0.0
6,7.0,CF,Luis Robert,23.0,68.0,296.0,275.0,42.0,93.0,22.0,...,0.378,0.567,0.946,155.0,156.0,4.0,5.0,0.0,2.0,1.0
7,8.0,RF,Adam Eaton,32.0,58.0,219.0,189.0,33.0,38.0,8.0,...,0.298,0.344,0.642,76.0,65.0,5.0,6.0,4.0,0.0,0.0
8,9.0,DH,Yermin Mercedes,28.0,68.0,262.0,240.0,26.0,65.0,9.0,...,0.328,0.404,0.732,100.0,97.0,7.0,1.0,0.0,1.0,1.0
9,10.0,UT,Leury Garcia,30.0,126.0,474.0,415.0,60.0,111.0,22.0,...,0.335,0.376,0.711,96.0,156.0,12.0,4.0,9.0,5.0,0.0
10,11.0,OF,Brian Goodwin,30.0,72.0,271.0,235.0,33.0,52.0,10.0,...,0.319,0.374,0.693,90.0,88.0,2.0,1.0,1.0,1.0,0.0
11,12.0,LF,Eloy Jimenez,24.0,55.0,231.0,213.0,23.0,53.0,10.0,...,0.303,0.437,0.740,100.0,93.0,8.0,1.0,0.0,1.0,0.0
12,13.0,C,Zack Collins,26.0,78.0,231.0,195.0,25.0,41.0,13.0,...,0.330,0.338,0.669,85.0,66.0,4.0,1.0,1.0,0.0,1.0
13,14.0,2B,Nick Madrigal,24.0,54.0,215.0,200.0,30.0,61.0,10.0,...,0.349,0.425,0.774,112.0,85.0,3.0,3.0,0.0,1.0,0.0
14,15.0,MI,Danny Mendick,27.0,71.0,186.0,164.0,14.0,36.0,5.0,...,0.303,0.287,0.589,64.0,47.0,1.0,2.0,1.0,1.0,0.0
15,16.0,DH,Gavin Sheets,25.0,54.0,179.0,160.0,23.0,40.0,8.0,...,0.324,0.506,0.830,123.0,81.0,4.0,2.0,0.0,1.0,0.0
16,17.0,CF,Adam Engel,29.0,39.0,140.0,123.0,21.0,31.0,9.0,...,0.336,0.496,0.832,124.0,61.0,4.0,5.0,0.0,1.0,0.0
17,18.0,CF,Billy Hamilton,30.0,71.0,135.0,127.0,23.0,28.0,8.0,...,0.242,0.378,0.620,67.0,48.0,1.0,0.0,3.0,1.0,0.0
18,19.0,UT,Jake Lamb,30.0,43.0,131.0,113.0,20.0,24.0,2.0,...,0.321,0.389,0.710,94.0,44.0,4.0,1.0,0.0,0.0,0.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
def new_row(row):
    return (row['2B'] +row['3B']+row ['HR'])/row['AB']

hitters_qualified ['new_row'] = hitters_qualified.apply(new_row, axis=1)

hitters_qualified [['Pos','Name','new_row']].sort_values('new_row')

    Pos             Name   new_row
2    2B  Cesar Hernandez  0.036082
14   MI    Danny Mendick  0.042683
18   UT        Jake Lamb  0.070796
8    DH  Yermin Mercedes  0.070833
9    UT     Leury Garcia  0.074699
7    RF       Adam Eaton  0.079365
13   2B    Nick Madrigal  0.080000
10   OF    Brian Goodwin  0.080851
12    C     Zack Collins  0.087179
5    LF    Andrew Vaughn  0.088729
3    SS     Tim Anderson  0.091082
4    3B     Yoan Moncada  0.092308
11   LF     Eloy Jimenez  0.093897
17   CF   Billy Hamilton  0.102362
1    1B       José Abreu  0.109541
0     C  Yasmani Grandal  0.114695
15   DH     Gavin Sheets  0.118750
16   CF       Adam Engel  0.130081
6    CF      Luis Robert  0.130909
19  NaN              NaN       NaN
20  NaN              NaN       NaN
21  NaN              NaN       NaN
22  NaN              NaN       NaN
23  NaN              NaN       NaN